/**
 * Nationality -> flag emoji. Keys are the exact, complete set of
 * `players.nationality` strings confirmed live against the database
 * (`select distinct value from player_nationalities` — 211 real values,
 * 2026-08-31) — not a generic country list, this file only needs to
 * cover what SCOUTASTIC actually returns for this field. A name with no
 * entry here (should not happen for a real nationality value, but data
 * can always surprise) renders no flag rather than a guessed one — see
 * `flagForNationality()`.
 *
 * England/Scotland/Wales use the real Unicode subdivision flag tag
 * sequences (not a generic UK flag) since football nationality data
 * treats them as separate countries; Northern Ireland has no equivalent
 * Unicode subdivision flag, so it falls back to the UK flag.
 */
const NATIONALITY_TO_ISO2: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  Angola: "AO",
  "Antigua and Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Benin: "BJ",
  Bermuda: "BM",
  Bolivia: "BO",
  Bonaire: "BQ",
  "Bosnia-Herzegovina": "BA",
  Botswana: "BW",
  Brazil: "BR",
  "British Virgin Islands": "VG",
  "Brunei Darussalam": "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  "Chinese Taipei": "TW",
  Colombia: "CO",
  Comoros: "KM",
  Congo: "CG",
  "Costa Rica": "CR",
  "Cote d'Ivoire": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Curacao: "CW",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  "DR Congo": "CD",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  England: "GB-ENG",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Ethiopia: "ET",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  Gabon: "GA",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guernsey: "GG",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Haiti: "HT",
  Honduras: "HN",
  Hongkong: "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  "Isle of Man": "IM",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jersey: "JE",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  "Korea, South": "KR",
  Kosovo: "XK",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  Macedonia: "MK",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Mali: "ML",
  Malta: "MT",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  Moldova: "MD",
  "Moldova, Republic of": "MD",
  Mongolia: "MN",
  Montenegro: "ME",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nepal: "NP",
  Netherlands: "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  "North Macedonia": "MK",
  "Northern Ireland": "GB", // no Unicode subdivision flag exists for Northern Ireland — falls back to the UK flag rather than guessing one
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palestine: "PS",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  Réunion: "RE",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  "Saint-Martin": "MF",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  Scotland: "GB-SCT",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  "Sint Maarten": "SX",
  Slovakia: "SK",
  Slovenia: "SI",
  Somalia: "SO",
  "South Africa": "ZA",
  "Southern Sudan": "SS",
  Spain: "ES",
  "Sri Lanka": "LK",
  "St. Kitts & Nevis": "KN",
  "St. Lucia": "LC",
  "St. Vincent & Grenadinen": "VC",
  Sudan: "SD",
  Suriname: "SR",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  "Syrian Arab Republic": "SY",
  Tahiti: "PF",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  "The Gambia": "GM",
  "Timor-Leste": "TL",
  Togo: "TG",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Türkiye: "TR",
  Turkmenistan: "TM",
  "Turks- and Caicosinseln": "TC",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United Kingdom": "GB",
  "United States": "US",
  "United States of America": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Vietnam: "VN",
  Wales: "GB-WLS",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

const REGIONAL_INDICATOR_BASE = 0x1f1e6; // Unicode 'A' regional indicator symbol
const TAG_BASE = 0xe0000; // Unicode tag block base, used for subdivision flag sequences

function flagFromIso2(iso2: string): string {
  return String.fromCodePoint(...[...iso2.toUpperCase()].map((c) => REGIONAL_INDICATOR_BASE + c.charCodeAt(0) - 65));
}

/**
 * England/Scotland/Wales use the real "black flag + tag sequence" emoji,
 * e.g. 🏴󠁧󠁢󠁥󠁮󠁧󠁿 — not a generic ISO2 flag. The tag sequence encodes the
 * ISO 3166-2 subdivision code as plain letters with no punctuation
 * ("gbeng", not "gb-eng") — stripping the hyphen here rather than
 * storing hyphen-free codes above keeps the map entries readable.
 */
function subdivisionFlag(code: string): string {
  const tagChars = [...code.toLowerCase().replace(/[^a-z]/g, "")].map((c) => String.fromCodePoint(TAG_BASE + c.charCodeAt(0)));
  return "\u{1F3F4}" + tagChars.join("") + "\u{E007F}";
}

/** Real flag for a `players.nationality` value, or `null` if this exact string isn't one of the 211 confirmed real values — never a guessed fallback. */
export function flagForNationality(nationality: string | null): string | null {
  if (!nationality) return null;
  const code = NATIONALITY_TO_ISO2[nationality];
  if (!code) return null;
  if (code.startsWith("GB-")) return subdivisionFlag(code);
  return flagFromIso2(code);
}
