/**
 * AI Scouting Tips — see docs/AI_TIPS.md. Generated by
 * scripts/generate-ai-tips.mjs (scheduled GitHub Action), never at
 * request time — the frontend only ever reads the most recent run.
 */

export interface AiTip {
  title: string;
  detail: string;
}

export interface AiTipsDigest {
  generatedAt: string; // ISO datetime
  model: string;
  tips: AiTip[];
}
