import type { Player } from "./types";

/**
 * ============================================================================
 * DEMO DATA — NOT REAL SCOUTING RECORDS
 * ============================================================================
 * Every player, club affiliation, rating and note below is fictional and
 * exists only to exercise the UI. This file is the single seam that gets
 * removed in Phase 2 onward:
 *
 *   Phase 2 (SCOUTASTIC) -> replaces player profile + club/competition data
 *   Phase 3 (PostgreSQL) -> replaces in-memory status/notes/shortlist state
 *   Phase 4 (SofaScore)  -> replaces the `matches` rating history
 *   Phase 5 (Sync)       -> keeps all of the above fresh automatically
 *
 * Every component reads players through `lib/demo-data/index.ts` selectors,
 * never this array directly, so swapping the source stays a one-file change.
 * ============================================================================
 */
export const DEMO_PLAYERS: Player[] = [
  {
    id: "p01",
    name: "Amara Diallo",
    photoUrl: null,
    dateOfBirth: "2006-03-14",
    nationality: "Mali",
    isAfrican: true,
    position: "ST",
    club: "Fehérvár FC",
    league: "NB I",
    leagueCountry: "Hungary",
    isEasternEuropeanLeague: true,
    heightCm: 183,
    preferredFoot: "Right",
    marketValueEUR: 1800000,
    contractExpiry: "2028-06-30",
    status: "priority",
    addedDate: "2026-08-18",
    isDebutant: true,
    debutDate: "2026-08-10",
    isYouthOrReserve: false,
    notes: {
      strengths: "Explosive first step, strong in transition, clinical with his first touch inside the box.",
      weaknesses: "Needs to add upper-body strength to hold off Eastern European CBs.",
      recommendation: "Track over the next 5 fixtures before initiating contact.",
      general: "Debut goal came off the bench in the 78th minute against Paksi SE.",
    },
    matches: [
      { date: "2026-08-24", competition: "NB I", opponent: "Paksi SE", result: "2-1 W", minutes: 90, starter: true, rating: 7.6 },
      { date: "2026-08-17", competition: "NB I", opponent: "Kecskeméti TE", result: "1-1 D", minutes: 81, starter: true, rating: 7.1 },
      { date: "2026-08-10", competition: "NB I", opponent: "Paksi SE", result: "3-0 W", minutes: 22, starter: false, rating: 7.9 },
      { date: "2026-08-03", competition: "NB I", opponent: "Diósgyőr", result: "0-0 D", minutes: 0, starter: false, rating: null },
      { date: "2026-07-27", competition: "NB I", opponent: "Puskás Akadémia", result: "1-2 L", minutes: 0, starter: false, rating: null },
    ],
  },
  {
    id: "p02",
    name: "Chidi Nwosu",
    photoUrl: null,
    dateOfBirth: "2005-11-02",
    nationality: "Nigeria",
    isAfrican: true,
    position: "RW",
    club: "Ludogorets Razgrad",
    league: "First League",
    leagueCountry: "Bulgaria",
    isEasternEuropeanLeague: true,
    heightCm: 176,
    preferredFoot: "Left",
    marketValueEUR: 2500000,
    contractExpiry: "2027-06-30",
    status: "interested",
    addedDate: "2026-08-05",
    isDebutant: true,
    debutDate: "2026-07-22",
    isYouthOrReserve: false,
    notes: {
      strengths: "Inverted winger with a genuine left foot, high volume of successful dribbles per 90.",
      weaknesses: "Defensive work rate drops off after the 70th minute.",
      recommendation: "Arrange in-person report at next home fixture.",
      general: "Started every league match since his debut cameo.",
    },
    matches: [
      { date: "2026-08-23", competition: "First League", opponent: "CSKA Sofia", result: "2-0 W", minutes: 90, starter: true, rating: 8.1 },
      { date: "2026-08-16", competition: "First League", opponent: "Levski Sofia", result: "1-1 D", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-08-09", competition: "First League", opponent: "Botev Plovdiv", result: "3-1 W", minutes: 78, starter: true, rating: 8.4 },
      { date: "2026-07-30", competition: "First League", opponent: "Cherno More", result: "2-1 W", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-07-22", competition: "First League", opponent: "Arda Kardzhali", result: "1-0 W", minutes: 31, starter: false, rating: 7.5 },
    ],
  },
  {
    id: "p03",
    name: "Kwame Asante",
    photoUrl: null,
    dateOfBirth: "2003-01-27",
    nationality: "Ghana",
    isAfrican: true,
    position: "CB",
    club: "Śląsk Wrocław",
    league: "Ekstraklasa",
    leagueCountry: "Poland",
    isEasternEuropeanLeague: true,
    heightCm: 191,
    preferredFoot: "Right",
    marketValueEUR: 1200000,
    contractExpiry: "2027-12-31",
    status: "monitoring",
    addedDate: "2026-06-14",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Commanding in the air, comfortable playing out from the back under pressure.",
      weaknesses: "Recovery pace can be exposed against direct wingers.",
      recommendation: "Continue monitoring, revisit after winter break.",
      general: "Vice-captain of the U23 side before breaking into the first team.",
    },
    matches: [
      { date: "2026-08-22", competition: "Ekstraklasa", opponent: "Legia Warszawa", result: "0-2 L", minutes: 90, starter: true, rating: 6.4 },
      { date: "2026-08-15", competition: "Ekstraklasa", opponent: "Lech Poznań", result: "1-1 D", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-08-08", competition: "Ekstraklasa", opponent: "Raków Częstochowa", result: "2-1 W", minutes: 90, starter: true, rating: 7.3 },
      { date: "2026-08-01", competition: "Ekstraklasa", opponent: "Jagiellonia Białystok", result: "1-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-07-25", competition: "Ekstraklasa", opponent: "Pogoń Szczecin", result: "0-0 D", minutes: 90, starter: true, rating: 6.7 },
    ],
  },
  {
    id: "p04",
    name: "Youssef Idrissi",
    photoUrl: null,
    dateOfBirth: "2004-09-09",
    nationality: "Morocco",
    isAfrican: true,
    position: "AM",
    club: "Sparta Praha",
    league: "Fortuna Liga",
    leagueCountry: "Czech Republic",
    isEasternEuropeanLeague: true,
    heightCm: 174,
    preferredFoot: "Right",
    marketValueEUR: 4500000,
    contractExpiry: "2028-06-30",
    status: "priority",
    addedDate: "2026-07-29",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Creative index among the highest in the league, excellent set-piece delivery.",
      weaknesses: "Needs to improve consistency away from home.",
      recommendation: "Priority target — schedule live match report before September window closes.",
      general: "Already linked with clubs in Germany and the Netherlands.",
    },
    matches: [
      { date: "2026-08-24", competition: "Fortuna Liga", opponent: "Slavia Praha", result: "1-1 D", minutes: 90, starter: true, rating: 8.2 },
      { date: "2026-08-17", competition: "Fortuna Liga", opponent: "Viktoria Plzeň", result: "2-0 W", minutes: 90, starter: true, rating: 8.6 },
      { date: "2026-08-10", competition: "Fortuna Liga", opponent: "Baník Ostrava", result: "3-1 W", minutes: 85, starter: true, rating: 8.0 },
      { date: "2026-08-03", competition: "Fortuna Liga", opponent: "Slovácko", result: "1-0 W", minutes: 90, starter: true, rating: 7.5 },
      { date: "2026-07-27", competition: "Fortuna Liga", opponent: "Bohemians 1905", result: "2-2 D", minutes: 90, starter: true, rating: 7.3 },
    ],
  },
  {
    id: "p05",
    name: "Ibrahima Diakhaté",
    photoUrl: null,
    dateOfBirth: "2006-05-19",
    nationality: "Senegal",
    isAfrican: true,
    position: "DM",
    club: "FCSB",
    league: "Liga 1",
    leagueCountry: "Romania",
    isEasternEuropeanLeague: true,
    heightCm: 186,
    preferredFoot: "Right",
    marketValueEUR: 900000,
    contractExpiry: "2029-06-30",
    status: "monitoring",
    addedDate: "2026-08-27",
    isDebutant: true,
    debutDate: "2026-08-25",
    isYouthOrReserve: false,
    notes: {
      strengths: "Reads the game well for his age, strong tackling technique.",
      weaknesses: "Only one senior appearance so far — sample size too small to judge.",
      recommendation: "Early stage, keep on watch list.",
      general: "Promoted from the youth academy mid-season.",
    },
    matches: [
      { date: "2026-08-25", competition: "Liga 1", opponent: "Universitatea Craiova", result: "1-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-18", competition: "Liga 1", opponent: "CFR Cluj", result: "0-1 L", minutes: 0, starter: false, rating: null },
      { date: "2026-08-11", competition: "Liga 1", opponent: "Rapid București", result: "2-2 D", minutes: 0, starter: false, rating: null },
      { date: "2026-08-04", competition: "Liga 1", opponent: "Farul Constanța", result: "1-1 D", minutes: 0, starter: false, rating: null },
      { date: "2026-07-28", competition: "Liga 1", opponent: "Universitatea Cluj", result: "3-0 W", minutes: 0, starter: false, rating: null },
    ],
  },
  {
    id: "p06",
    name: "Aristide Kouadio",
    photoUrl: null,
    dateOfBirth: "2002-12-08",
    nationality: "Ivory Coast",
    isAfrican: true,
    position: "LW",
    club: "Dinamo Zagreb",
    league: "HNL",
    leagueCountry: "Croatia",
    isEasternEuropeanLeague: true,
    heightCm: 179,
    preferredFoot: "Right",
    marketValueEUR: 6500000,
    contractExpiry: "2027-06-30",
    status: "interested",
    addedDate: "2026-05-11",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Champions League experience, elite acceleration over 10-20m.",
      weaknesses: "Market value likely outside current recruitment budget.",
      recommendation: "Keep on file for future windows.",
      general: "Regular starter in continental competition this season.",
    },
    matches: [
      { date: "2026-08-23", competition: "HNL", opponent: "Hajduk Split", result: "2-1 W", minutes: 90, starter: true, rating: 7.8 },
      { date: "2026-08-16", competition: "HNL", opponent: "Rijeka", result: "1-0 W", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-08-09", competition: "HNL", opponent: "Osijek", result: "3-2 W", minutes: 90, starter: true, rating: 8.3 },
      { date: "2026-08-02", competition: "HNL", opponent: "Gorica", result: "2-0 W", minutes: 76, starter: true, rating: 7.1 },
      { date: "2026-07-26", competition: "HNL", opponent: "Slaven Belupo", result: "1-1 D", minutes: 90, starter: true, rating: 6.9 },
    ],
  },
  {
    id: "p07",
    name: "Emeka Adeyemi",
    photoUrl: null,
    dateOfBirth: "2005-07-30",
    nationality: "Nigeria",
    isAfrican: true,
    position: "RB",
    club: "Shakhtar Donetsk",
    league: "Ukrainian Premier League",
    leagueCountry: "Ukraine",
    isEasternEuropeanLeague: true,
    heightCm: 178,
    preferredFoot: "Right",
    marketValueEUR: 3200000,
    contractExpiry: "2028-06-30",
    status: "not_assessed",
    addedDate: "2026-07-02",
    isDebutant: true,
    debutDate: "2026-06-30",
    isYouthOrReserve: false,
    notes: {
      strengths: "Athletic full-back, strong overlapping runs.",
      weaknesses: "Positioning at the back post still developing.",
      recommendation: "Assign to scouting network for a first assessment.",
      general: "Part of Shakhtar's academy pipeline.",
    },
    matches: [
      { date: "2026-08-22", competition: "UPL", opponent: "Dynamo Kyiv", result: "1-1 D", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-08-15", competition: "UPL", opponent: "Vorskla Poltava", result: "2-0 W", minutes: 90, starter: true, rating: 7.5 },
      { date: "2026-08-08", competition: "UPL", opponent: "Kryvbas", result: "1-0 W", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-08-01", competition: "UPL", opponent: "Zorya Luhansk", result: "3-1 W", minutes: 90, starter: true, rating: 7.6 },
      { date: "2026-06-30", competition: "UPL", opponent: "Polissya Zhytomyr", result: "2-1 W", minutes: 19, starter: false, rating: 6.9 },
    ],
  },
  {
    id: "p08",
    name: "Baba Traoré",
    photoUrl: null,
    dateOfBirth: "2001-04-16",
    nationality: "Mali",
    isAfrican: true,
    position: "CM",
    club: "CFR Cluj",
    league: "Liga 1",
    leagueCountry: "Romania",
    isEasternEuropeanLeague: true,
    heightCm: 181,
    preferredFoot: "Both",
    marketValueEUR: 2100000,
    contractExpiry: "2027-06-30",
    status: "monitoring",
    addedDate: "2026-04-20",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Box-to-box engine, covers ground defensively and offensively.",
      weaknesses: "Discipline — averaging a high number of bookings.",
      recommendation: "Monitor disciplinary record alongside performance.",
      general: "Long-serving squad player, well regarded by teammates.",
    },
    matches: [
      { date: "2026-08-24", competition: "Liga 1", opponent: "FCSB", result: "1-1 D", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-17", competition: "Liga 1", opponent: "Universitatea Craiova", result: "2-1 W", minutes: 90, starter: true, rating: 7.3 },
      { date: "2026-08-10", competition: "Liga 1", opponent: "Rapid București", result: "0-0 D", minutes: 90, starter: true, rating: 6.5 },
      { date: "2026-08-03", competition: "Liga 1", opponent: "Farul Constanța", result: "1-0 W", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-07-27", competition: "Liga 1", opponent: "Sepsi OSK", result: "2-0 W", minutes: 90, starter: true, rating: 7.1 },
    ],
  },
  {
    id: "p09",
    name: "Patrick Mensah",
    photoUrl: null,
    dateOfBirth: "2004-02-22",
    nationality: "Ghana",
    isAfrican: true,
    position: "LB",
    club: "Slovan Bratislava",
    league: "Niké Liga",
    leagueCountry: "Slovakia",
    isEasternEuropeanLeague: true,
    heightCm: 177,
    preferredFoot: "Left",
    marketValueEUR: 1500000,
    contractExpiry: "2026-12-31",
    status: "interested",
    addedDate: "2026-06-30",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Natural left foot, dangerous from wide free kicks.",
      weaknesses: "Contract expiring soon — verify release clause status.",
      recommendation: "Contract situation makes this a value opportunity.",
      general: "Champions League qualifying rounds experience.",
    },
    matches: [
      { date: "2026-08-23", competition: "Niké Liga", opponent: "Spartak Trnava", result: "2-0 W", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-08-16", competition: "Niké Liga", opponent: "MFK Ružomberok", result: "1-1 D", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-08-09", competition: "Niké Liga", opponent: "DAC Dunajská Streda", result: "3-1 W", minutes: 90, starter: true, rating: 7.7 },
      { date: "2026-08-02", competition: "Niké Liga", opponent: "Žilina", result: "1-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-07-26", competition: "Niké Liga", opponent: "Trenčín", result: "2-2 D", minutes: 90, starter: true, rating: 6.6 },
    ],
  },
  {
    id: "p10",
    name: "Karim Belhadj",
    photoUrl: null,
    dateOfBirth: "2005-10-11",
    nationality: "Algeria",
    isAfrican: true,
    position: "ST",
    club: "Botev Plovdiv",
    league: "First League",
    leagueCountry: "Bulgaria",
    isEasternEuropeanLeague: true,
    heightCm: 185,
    preferredFoot: "Right",
    marketValueEUR: 1100000,
    contractExpiry: "2028-06-30",
    status: "not_assessed",
    addedDate: "2026-08-12",
    isDebutant: true,
    debutDate: "2026-08-05",
    isYouthOrReserve: false,
    notes: {
      strengths: "Strong hold-up play, good aerial threat at set pieces.",
      weaknesses: "Still learning to time runs against a high line.",
      recommendation: "Assign scout for live viewing next month.",
      general: "Scored on his senior debut from the bench.",
    },
    matches: [
      { date: "2026-08-23", competition: "First League", opponent: "Cherno More", result: "1-0 W", minutes: 90, starter: true, rating: 7.3 },
      { date: "2026-08-16", competition: "First League", opponent: "Arda Kardzhali", result: "2-1 W", minutes: 79, starter: true, rating: 7.5 },
      { date: "2026-08-05", competition: "First League", opponent: "Slavia Sofia", result: "2-0 W", minutes: 25, starter: false, rating: 7.8 },
      { date: "2026-07-29", competition: "First League", opponent: "Beroe", result: "1-1 D", minutes: 0, starter: false, rating: null },
      { date: "2026-07-22", competition: "First League", opponent: "Septemvri Sofia", result: "0-0 D", minutes: 0, starter: false, rating: null },
    ],
  },
  {
    id: "p11",
    name: "Junior Mbeki",
    photoUrl: null,
    dateOfBirth: "2006-01-05",
    nationality: "DR Congo",
    isAfrican: true,
    position: "CB",
    club: "Dinamo Tbilisi",
    league: "Erovnuli Liga",
    leagueCountry: "Georgia",
    isEasternEuropeanLeague: true,
    heightCm: 189,
    preferredFoot: "Right",
    marketValueEUR: 450000,
    contractExpiry: "2028-12-31",
    status: "monitoring",
    addedDate: "2026-07-20",
    isDebutant: true,
    debutDate: "2026-07-15",
    isYouthOrReserve: false,
    notes: {
      strengths: "Physically dominant for his age, comfortable in a back three.",
      weaknesses: "Small league sample — needs cross-checking against stronger opposition.",
      recommendation: "Add to long-term development watch list.",
      general: "Recruited from a Kinshasa academy last winter.",
    },
    matches: [
      { date: "2026-08-22", competition: "Erovnuli Liga", opponent: "Dinamo Batumi", result: "1-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-15", competition: "Erovnuli Liga", opponent: "Torpedo Kutaisi", result: "2-2 D", minutes: 90, starter: true, rating: 6.6 },
      { date: "2026-08-08", competition: "Erovnuli Liga", opponent: "Samgurali", result: "1-0 W", minutes: 90, starter: true, rating: 7.1 },
      { date: "2026-07-15", competition: "Erovnuli Liga", opponent: "Gagra", result: "3-0 W", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-07-08", competition: "Erovnuli Liga", opponent: "Kolkheti Poti", result: "0-1 L", minutes: 0, starter: false, rating: null },
    ],
  },
  {
    id: "p12",
    name: "Marek Novák",
    photoUrl: null,
    dateOfBirth: "1998-06-25",
    nationality: "Czech Republic",
    isAfrican: false,
    position: "GK",
    club: "Slavia Praha",
    league: "Fortuna Liga",
    leagueCountry: "Czech Republic",
    isEasternEuropeanLeague: true,
    heightCm: 193,
    preferredFoot: "Right",
    marketValueEUR: 3800000,
    contractExpiry: "2027-06-30",
    status: "interested",
    addedDate: "2026-03-02",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Excellent shot-stopper, commands his box well on crosses.",
      weaknesses: "Distribution under pressure could be sharper.",
      recommendation: "Strong backup / potential starter option.",
      general: "European qualification experience with current club.",
    },
    matches: [
      { date: "2026-08-24", competition: "Fortuna Liga", opponent: "Sparta Praha", result: "1-1 D", minutes: 90, starter: true, rating: 7.5 },
      { date: "2026-08-17", competition: "Fortuna Liga", opponent: "Slovácko", result: "2-0 W", minutes: 90, starter: true, rating: 7.8 },
      { date: "2026-08-10", competition: "Fortuna Liga", opponent: "Baník Ostrava", result: "1-0 W", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-08-03", competition: "Fortuna Liga", opponent: "Bohemians 1905", result: "0-0 D", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-07-27", competition: "Fortuna Liga", opponent: "Viktoria Plzeň", result: "1-2 L", minutes: 90, starter: true, rating: 6.4 },
    ],
  },
  {
    id: "p13",
    name: "Tomasz Kowalski",
    photoUrl: null,
    dateOfBirth: "2000-08-13",
    nationality: "Poland",
    isAfrican: false,
    position: "CB",
    club: "Legia Warszawa",
    league: "Ekstraklasa",
    leagueCountry: "Poland",
    isEasternEuropeanLeague: true,
    heightCm: 190,
    preferredFoot: "Left",
    marketValueEUR: 2800000,
    contractExpiry: "2027-06-30",
    status: "rejected",
    addedDate: "2026-02-11",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Left-footed centre back, good in build-up play.",
      weaknesses: "Pace is a concern against elite attackers — confirmed over three live views.",
      recommendation: "Not a fit for the current recruitment profile.",
      general: "Closed out after in-person assessment in June.",
    },
    matches: [
      { date: "2026-08-22", competition: "Ekstraklasa", opponent: "Śląsk Wrocław", result: "2-0 W", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-08-15", competition: "Ekstraklasa", opponent: "Lech Poznań", result: "1-1 D", minutes: 90, starter: true, rating: 6.5 },
      { date: "2026-08-08", competition: "Ekstraklasa", opponent: "Raków Częstochowa", result: "0-1 L", minutes: 90, starter: true, rating: 6.1 },
      { date: "2026-08-01", competition: "Ekstraklasa", opponent: "Jagiellonia Białystok", result: "2-1 W", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-07-25", competition: "Ekstraklasa", opponent: "Pogoń Szczecin", result: "1-1 D", minutes: 90, starter: true, rating: 6.4 },
    ],
  },
  {
    id: "p14",
    name: "Filip Horváth",
    photoUrl: null,
    dateOfBirth: "2003-05-17",
    nationality: "Hungary",
    isAfrican: false,
    position: "DM",
    club: "Ferencváros",
    league: "NB I",
    leagueCountry: "Hungary",
    isEasternEuropeanLeague: true,
    heightCm: 182,
    preferredFoot: "Right",
    marketValueEUR: 2200000,
    contractExpiry: "2028-06-30",
    status: "monitoring",
    addedDate: "2026-05-30",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Excellent positioning, breaks up play efficiently.",
      weaknesses: "Limited progressive passing range so far.",
      recommendation: "Continue monitoring domestically and in Europa League.",
      general: "Full Hungary U21 international.",
    },
    matches: [
      { date: "2026-08-23", competition: "NB I", opponent: "Puskás Akadémia", result: "3-0 W", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-08-16", competition: "NB I", opponent: "Fehérvár FC", result: "1-1 D", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-08-09", competition: "NB I", opponent: "Kecskeméti TE", result: "2-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-02", competition: "NB I", opponent: "Diósgyőr", result: "1-0 W", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-07-26", competition: "NB I", opponent: "Paksi SE", result: "0-0 D", minutes: 90, starter: true, rating: 6.5 },
    ],
  },
  {
    id: "p15",
    name: "Nikola Petrović",
    photoUrl: null,
    dateOfBirth: "1999-09-21",
    nationality: "Serbia",
    isAfrican: false,
    position: "CM",
    club: "Crvena Zvezda",
    league: "Super Liga",
    leagueCountry: "Serbia",
    isEasternEuropeanLeague: true,
    heightCm: 180,
    preferredFoot: "Both",
    marketValueEUR: 5200000,
    contractExpiry: "2027-06-30",
    status: "interested",
    addedDate: "2026-04-08",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Complete midfielder, Champions League group stage minutes.",
      weaknesses: "Likely to attract higher-budget suitors.",
      recommendation: "Long shot but worth a formal enquiry.",
      general: "Serbia senior international.",
    },
    matches: [
      { date: "2026-08-24", competition: "Super Liga", opponent: "Partizan", result: "2-1 W", minutes: 90, starter: true, rating: 8.0 },
      { date: "2026-08-17", competition: "Super Liga", opponent: "TSC Bačka Topola", result: "3-0 W", minutes: 76, starter: true, rating: 7.6 },
      { date: "2026-08-10", competition: "Super Liga", opponent: "Vojvodina", result: "1-1 D", minutes: 90, starter: true, rating: 7.1 },
      { date: "2026-08-03", competition: "Super Liga", opponent: "Radnički Niš", result: "2-0 W", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-07-27", competition: "Super Liga", opponent: "Čukarički", result: "1-0 W", minutes: 90, starter: true, rating: 7.2 },
    ],
  },
  {
    id: "p16",
    name: "Andrei Popescu",
    photoUrl: null,
    dateOfBirth: "2004-12-30",
    nationality: "Romania",
    isAfrican: false,
    position: "AM",
    club: "FCSB",
    league: "Liga 1",
    leagueCountry: "Romania",
    isEasternEuropeanLeague: true,
    heightCm: 173,
    preferredFoot: "Left",
    marketValueEUR: 3000000,
    contractExpiry: "2028-06-30",
    status: "priority",
    addedDate: "2026-08-01",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Highest chance-creation numbers in Liga 1 this season.",
      weaknesses: "Injury history — check medical record before formal offer.",
      recommendation: "Priority target pending medical review.",
      general: "Romania U21 captain.",
    },
    matches: [
      { date: "2026-08-24", competition: "Liga 1", opponent: "CFR Cluj", result: "1-1 D", minutes: 90, starter: true, rating: 7.7 },
      { date: "2026-08-17", competition: "Liga 1", opponent: "Universitatea Craiova", result: "2-1 W", minutes: 90, starter: true, rating: 8.1 },
      { date: "2026-08-10", competition: "Liga 1", opponent: "Rapid București", result: "0-0 D", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-03", competition: "Liga 1", opponent: "Farul Constanța", result: "3-1 W", minutes: 90, starter: true, rating: 8.3 },
      { date: "2026-07-27", competition: "Liga 1", opponent: "Sepsi OSK", result: "1-0 W", minutes: 90, starter: true, rating: 7.4 },
    ],
  },
  {
    id: "p17",
    name: "Luka Marić",
    photoUrl: null,
    dateOfBirth: "2002-07-04",
    nationality: "Croatia",
    isAfrican: false,
    position: "LW",
    club: "Hajduk Split",
    league: "HNL",
    leagueCountry: "Croatia",
    isEasternEuropeanLeague: true,
    heightCm: 178,
    preferredFoot: "Right",
    marketValueEUR: 4100000,
    contractExpiry: "2026-12-31",
    status: "monitoring",
    addedDate: "2026-03-25",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Direct dribbler, cuts inside well onto his stronger foot.",
      weaknesses: "Contract expiring in December — verify agent situation.",
      recommendation: "Free-agent opportunity in six months, monitor closely.",
      general: "Vocal on-field leader despite his age.",
    },
    matches: [
      { date: "2026-08-23", competition: "HNL", opponent: "Dinamo Zagreb", result: "1-2 L", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-08-16", competition: "HNL", opponent: "Rijeka", result: "2-2 D", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-09", competition: "HNL", opponent: "Osijek", result: "3-0 W", minutes: 90, starter: true, rating: 7.8 },
      { date: "2026-08-02", competition: "HNL", opponent: "Gorica", result: "1-0 W", minutes: 90, starter: true, rating: 7.1 },
      { date: "2026-07-26", competition: "HNL", opponent: "Slaven Belupo", result: "2-1 W", minutes: 90, starter: true, rating: 7.3 },
    ],
  },
  {
    id: "p18",
    name: "Dario Novoselić",
    photoUrl: null,
    dateOfBirth: "2005-02-18",
    nationality: "Bosnia & Herzegovina",
    isAfrican: false,
    position: "RW",
    club: "Željezničar",
    league: "Premier League of BiH",
    leagueCountry: "Bosnia & Herzegovina",
    isEasternEuropeanLeague: true,
    heightCm: 175,
    preferredFoot: "Left",
    marketValueEUR: 700000,
    contractExpiry: "2027-06-30",
    status: "not_assessed",
    addedDate: "2026-08-20",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Pace and directness in transition.",
      weaknesses: "Not yet assessed in person.",
      recommendation: "Awaiting first scouting report.",
      general: "Flagged via SofaScore heat-map screening.",
    },
    matches: [
      { date: "2026-08-22", competition: "Premier League of BiH", opponent: "Sarajevo", result: "0-1 L", minutes: 90, starter: true, rating: 6.3 },
      { date: "2026-08-15", competition: "Premier League of BiH", opponent: "Borac Banja Luka", result: "1-1 D", minutes: 90, starter: true, rating: 6.6 },
      { date: "2026-08-08", competition: "Premier League of BiH", opponent: "Zrinjski Mostar", result: "2-1 W", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-08-01", competition: "Premier League of BiH", opponent: "Velež Mostar", result: "1-0 W", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-07-25", competition: "Premier League of BiH", opponent: "Tuzla City", result: "0-0 D", minutes: 90, starter: true, rating: 6.4 },
    ],
  },
  {
    id: "p19",
    name: "Oleksandr Bondarenko",
    photoUrl: null,
    dateOfBirth: "2001-03-29",
    nationality: "Ukraine",
    isAfrican: false,
    position: "ST",
    club: "Dynamo Kyiv",
    league: "Ukrainian Premier League",
    leagueCountry: "Ukraine",
    isEasternEuropeanLeague: true,
    heightCm: 187,
    preferredFoot: "Right",
    marketValueEUR: 7000000,
    contractExpiry: "2028-06-30",
    status: "interested",
    addedDate: "2026-05-02",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Clinical finisher, strong movement in the channels.",
      weaknesses: "Market value likely to rise further with continued form.",
      recommendation: "Formal enquiry recommended before valuation climbs.",
      general: "Top scorer in the league this season.",
    },
    matches: [
      { date: "2026-08-22", competition: "UPL", opponent: "Shakhtar Donetsk", result: "1-1 D", minutes: 90, starter: true, rating: 7.5 },
      { date: "2026-08-15", competition: "UPL", opponent: "Vorskla Poltava", result: "3-1 W", minutes: 90, starter: true, rating: 8.5 },
      { date: "2026-08-08", competition: "UPL", opponent: "Kryvbas", result: "2-0 W", minutes: 90, starter: true, rating: 7.9 },
      { date: "2026-08-01", competition: "UPL", opponent: "Zorya Luhansk", result: "4-1 W", minutes: 90, starter: true, rating: 8.7 },
      { date: "2026-07-25", competition: "UPL", opponent: "Polissya Zhytomyr", result: "1-0 W", minutes: 90, starter: true, rating: 7.2 },
    ],
  },
  {
    id: "p20",
    name: "Giorgi Kapanadze",
    photoUrl: null,
    dateOfBirth: "2000-10-06",
    nationality: "Georgia",
    isAfrican: false,
    position: "CB",
    club: "Dinamo Tbilisi",
    league: "Erovnuli Liga",
    leagueCountry: "Georgia",
    isEasternEuropeanLeague: true,
    heightCm: 188,
    preferredFoot: "Right",
    marketValueEUR: 600000,
    contractExpiry: "2027-06-30",
    status: "rejected",
    addedDate: "2026-01-15",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Solid positional sense in a back four.",
      weaknesses: "Ball-playing ability below the level required.",
      recommendation: "Not pursuing further.",
      general: "Assessed twice in person this season.",
    },
    matches: [
      { date: "2026-08-22", competition: "Erovnuli Liga", opponent: "Torpedo Kutaisi", result: "1-0 W", minutes: 90, starter: true, rating: 6.5 },
      { date: "2026-08-15", competition: "Erovnuli Liga", opponent: "Samgurali", result: "0-0 D", minutes: 90, starter: true, rating: 6.2 },
      { date: "2026-08-08", competition: "Erovnuli Liga", opponent: "Gagra", result: "2-1 W", minutes: 90, starter: true, rating: 6.6 },
      { date: "2026-08-01", competition: "Erovnuli Liga", opponent: "Kolkheti Poti", result: "1-1 D", minutes: 90, starter: true, rating: 6.1 },
      { date: "2026-07-25", competition: "Erovnuli Liga", opponent: "Dinamo Batumi", result: "0-2 L", minutes: 90, starter: true, rating: 5.8 },
    ],
  },
  {
    id: "p21",
    name: "Emils Ozols",
    photoUrl: null,
    dateOfBirth: "2003-06-11",
    nationality: "Latvia",
    isAfrican: false,
    position: "RB",
    club: "Riga FC",
    league: "Virslīga",
    leagueCountry: "Latvia",
    isEasternEuropeanLeague: true,
    heightCm: 179,
    preferredFoot: "Right",
    marketValueEUR: 500000,
    contractExpiry: "2027-12-31",
    status: "not_assessed",
    addedDate: "2026-08-22",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Consistent starter, good delivery from wide areas.",
      weaknesses: "Not yet assessed in person.",
      recommendation: "Add to network report queue.",
      general: "Latvia full international.",
    },
    matches: [
      { date: "2026-08-21", competition: "Virslīga", opponent: "Valmiera", result: "2-0 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-14", competition: "Virslīga", opponent: "RFS", result: "1-1 D", minutes: 90, starter: true, rating: 6.7 },
      { date: "2026-08-07", competition: "Virslīga", opponent: "Auda", result: "3-0 W", minutes: 90, starter: true, rating: 7.3 },
      { date: "2026-07-31", competition: "Virslīga", opponent: "Metta", result: "1-0 W", minutes: 90, starter: true, rating: 6.9 },
      { date: "2026-07-24", competition: "Virslīga", opponent: "Liepāja", result: "0-0 D", minutes: 90, starter: true, rating: 6.5 },
    ],
  },
  {
    id: "p22",
    name: "Anton Petrauskas",
    photoUrl: null,
    dateOfBirth: "2004-04-03",
    nationality: "Lithuania",
    isAfrican: false,
    position: "CM",
    club: "Žalgiris Vilnius",
    league: "A Lyga",
    leagueCountry: "Lithuania",
    isEasternEuropeanLeague: true,
    heightCm: 181,
    preferredFoot: "Left",
    marketValueEUR: 400000,
    contractExpiry: "2028-06-30",
    status: "monitoring",
    addedDate: "2026-07-10",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Progressive passer, calm in possession.",
      weaknesses: "League level significantly below target competitions.",
      recommendation: "Keep on watch list for continued development.",
      general: "Regular for Lithuania U21s.",
    },
    matches: [
      { date: "2026-08-20", competition: "A Lyga", opponent: "Kauno Žalgiris", result: "1-1 D", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-08-13", competition: "A Lyga", opponent: "Panevėžys", result: "2-1 W", minutes: 90, starter: true, rating: 7.1 },
      { date: "2026-08-06", competition: "A Lyga", opponent: "Hegelmann", result: "0-0 D", minutes: 90, starter: true, rating: 6.5 },
      { date: "2026-07-30", competition: "A Lyga", opponent: "Riteriai", result: "3-1 W", minutes: 90, starter: true, rating: 7.4 },
      { date: "2026-07-23", competition: "A Lyga", opponent: "Dainava", result: "1-0 W", minutes: 90, starter: true, rating: 6.9 },
    ],
  },
  {
    id: "p23",
    name: "Bram Verhoeven",
    photoUrl: null,
    dateOfBirth: "2000-01-09",
    nationality: "Belgium",
    isAfrican: false,
    position: "CM",
    club: "KAA Gent",
    league: "Belgian Pro League",
    leagueCountry: "Belgium",
    isEasternEuropeanLeague: false,
    heightCm: 183,
    preferredFoot: "Right",
    marketValueEUR: 3500000,
    contractExpiry: "2027-06-30",
    status: "monitoring",
    addedDate: "2026-08-15",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Domestic league experience, adaptable across midfield roles.",
      weaknesses: "Squad rotation limiting recent minutes.",
      recommendation: "Track playing time over the next month.",
      general: "Known quantity in the Belgian top flight.",
    },
    matches: [
      { date: "2026-08-24", competition: "Belgian Pro League", opponent: "Club Brugge", result: "1-2 L", minutes: 90, starter: true, rating: 6.6 },
      { date: "2026-08-17", competition: "Belgian Pro League", opponent: "Cercle Brugge", result: "2-1 W", minutes: 90, starter: true, rating: 7.0 },
      { date: "2026-08-10", competition: "Belgian Pro League", opponent: "OH Leuven", result: "0-0 D", minutes: 90, starter: true, rating: 6.4 },
      { date: "2026-08-03", competition: "Belgian Pro League", opponent: "Charleroi", result: "1-0 W", minutes: 90, starter: true, rating: 6.8 },
      { date: "2026-07-27", competition: "Belgian Pro League", opponent: "STVV", result: "2-2 D", minutes: 90, starter: true, rating: 6.5 },
    ],
  },
  {
    id: "p24",
    name: "Younes El Ghazi",
    photoUrl: null,
    dateOfBirth: "2005-08-28",
    nationality: "Morocco",
    isAfrican: true,
    position: "RW",
    club: "Standard Liège",
    league: "Belgian Pro League",
    leagueCountry: "Belgium",
    isEasternEuropeanLeague: false,
    heightCm: 174,
    preferredFoot: "Left",
    marketValueEUR: 2600000,
    contractExpiry: "2028-06-30",
    status: "interested",
    addedDate: "2026-08-28",
    isDebutant: false,
    debutDate: null,
    isYouthOrReserve: false,
    notes: {
      strengths: "Sharp in one-on-one situations, improving end product.",
      weaknesses: "Consistency of end product still developing.",
      recommendation: "Domestic derby — easy to schedule an in-person view.",
      general: "Local candidate, straightforward logistics for scouting staff.",
    },
    matches: [
      { date: "2026-08-24", competition: "Belgian Pro League", opponent: "Genk", result: "2-1 W", minutes: 90, starter: true, rating: 7.6 },
      { date: "2026-08-17", competition: "Belgian Pro League", opponent: "Anderlecht", result: "1-1 D", minutes: 90, starter: true, rating: 7.2 },
      { date: "2026-08-10", competition: "Belgian Pro League", opponent: "Union SG", result: "0-1 L", minutes: 90, starter: true, rating: 6.5 },
      { date: "2026-08-03", competition: "Belgian Pro League", opponent: "Westerlo", result: "3-0 W", minutes: 82, starter: true, rating: 8.0 },
      { date: "2026-07-27", competition: "Belgian Pro League", opponent: "Mechelen", result: "1-1 D", minutes: 90, starter: true, rating: 6.8 },
    ],
  },
];
